name: Build Quectel-CM Package Debug

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/qosmio/openwrt-ipq.git
  REPO_BRANCH: 24.10-nss
  CONFIG_FILE: config/AW1000.config
  TZ: Asia/Kuala_Lumpur

jobs:
  quectel-cm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y $(curl -fsSL https://raw.githubusercontent.com/aNzTikTok/bin-nss/main/depend_ubuntu2204_openwrt)
        sudo timedatectl set-timezone "$TZ"

    - name: Clone OpenWrt Source
      run: |
        git clone --depth=1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Set Custom Feeds
      working-directory: ./openwrt
      run: |
        cat <<EOF > feeds.conf.default
        src-git packages https://git.openwrt.org/feed/packages.git;openwrt-24.10
        src-git luci https://git.openwrt.org/project/luci.git;openwrt-24.10
        src-git routing https://git.openwrt.org/feed/routing.git;openwrt-24.10
        src-git telephony https://git.openwrt.org/feed/telephony.git;openwrt-24.10
        src-git nss_packages https://github.com/qosmio/nss-packages.git;NSS-12.5-K6.x
        src-git sqm_scripts_nss https://github.com/qosmio/sqm-scripts-nss.git
        EOF

    - name: Update & Install Feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Apply .config and defconfig
      run: |
        cp -fv "${CONFIG_FILE}" openwrt/.config
        cd openwrt && make defconfig

    - name: Compile Quectel-CM Package
      working-directory: ./openwrt
      run: |
        make package/feeds/nss_packages/quectel-cm/compile -j1 V=s
